# Generated by Django 6.0.6 on 2026-06-15 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('description', models.TextField(verbose_name='Description')),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant couvert')),
                ('monthly_premium', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prime mensuelle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Produit d'assurance",
                'verbose_name_plural': "Produits d'assurance",
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='InsuranceSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name="Date d'expiration")),
                ('duration_months', models.IntegerField(verbose_name='Durée (mois)')),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prime mensuelle')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expiree', 'Expirée'), ('annulee', 'Annulée')], default='active', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Souscrit le')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_subscriptions', to='credits.loan', verbose_name='Prêt associé')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='insurance.insuranceplan', verbose_name='Produit')),
            ],
            options={
                'verbose_name': "Souscription d'assurance",
                'verbose_name_plural': "Souscriptions d'assurance",
                'ordering': ('-created_at',),
            },
        ),
    ]
