# Generated by Django 6.0.6 on 2026-06-15 21:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant demandé')),
                ('purpose', models.TextField(verbose_name='Objet du crédit')),
                ('status', models.CharField(choices=[('soumise', 'Soumise'), ('en_analyse', 'En analyse'), ('approuvee', 'Approuvée'), ('decaissée', 'Décaissée'), ('rejetee', 'Rejetée')], default='soumise', max_length=20, verbose_name='Statut')),
                ('eligibility_score', models.IntegerField(blank=True, null=True, verbose_name="Score d'éligibilité")),
                ('duration_months', models.IntegerField(verbose_name='Durée (mois)')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name="Taux d'intérêt mensuel (%)")),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Mensualité')),
                ('agent_notes', models.TextField(blank=True, verbose_name="Notes de l'agent")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('analyzed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyzed_loans', to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Demande de crédit',
                'verbose_name_plural': 'Demandes de crédit',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LoanDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='loans/documents/%Y/%m/', verbose_name='Fichier')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='credits.loan', verbose_name='Demande de prêt')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='LoanSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField(verbose_name="Numéro d'échéance")),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant payé')),
                ('status', models.CharField(choices=[('pending', 'À payer'), ('paid', 'Payé'), ('late', 'En retard')], default='pending', max_length=10, verbose_name='Statut')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='credits.loan', verbose_name='Prêt')),
            ],
            options={
                'verbose_name': 'Échéance',
                'verbose_name_plural': 'Échéances',
                'ordering': ('installment_number',),
            },
        ),
    ]
