# Generated by Django 6.0.6 on 2026-06-15 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('body', models.TextField(verbose_name='Message')),
                ('type', models.CharField(choices=[('loan_status', 'Changement de statut du crédit'), ('repayment', 'Remboursement enregistré'), ('insurance', "Souscription d'assurance"), ('system', 'Notification système')], default='system', max_length=20, verbose_name='Type')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='Lien')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lue')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ('-created_at',),
            },
        ),
    ]
